site_name: 王浩雄的个人主页
site_url: https://WangHX2024.github.io/blog
site_description: 王浩雄的个人主页
repo_name: "WangHX2024/blog"
repo_url: https://github.com/WangHX2024/blog
edit_uri: blob/master/docs
copyright: Copyright &copy; 2023 - 2025 WangHX</p>

theme:
  name: 'material'
  language: 'zh'
  icon: 
    logo: material/notebook-outline
    repo: fontawesome/brands/github
    edit: material/pencil
  custom_dir: overrides
  palette: 
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: 跟随系统
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 浅色模式
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 深色模式
  font:
    text: LXGW WenKai Screen GB Screen
    code: JetBrains Mono
  features:
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share
    - navigation.footer
    - content.action.view
    - content.code.copy
    - content.code.annotate

extra:
  generator: false
  social:
    - icon: fontawesome/brands/qq 
      link: https://3047901150.qzone.qq.com
      name: QQ空间
    - icon: fontawesome/brands/github 
      link: https://github.com/WangHX2024/
      name: GitHub
    - icon: fontawesome/solid/paper-plane
      link: mailto:<wanghaoxiong01@gmail.com>
      name: 电子邮件
  analytics:
    provider: google
    property: G-PLSZR8E9QE
    feedback:
      title: 激励
      ratings:
        - icon: fontawesome/regular/hand-back-fist
          name: 激励
          data: 1
          note: >- 
            <center> 感谢支持</center>

extra_css:
  - _css/extra.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css

plugins:
  - blog:
      blog_dir: blog
      blog_toc: true
  - search
  - glightbox
  - git-revision-date-localized:
      enable_creation_date: true
      type: datetime
      timezone: Asia/Shanghai
      locale: zh
      exclude:
        - index.md
        - comment.md
        - link.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

nav:
  - 主页 Home: 
    - index.md
    - 留言板: comment.md
    - 友链: link.md
  - 博客 Blog:
    - blog/index.md
  - 笔记 Note: 
    - note/index.md
    - Markdown 扩展语法: note/Markdown Extensions.md
  - 关于 About:
    - about/index.md

